Repository carloscuesta/gitmoji, pull requests merged in 2020-06, with the labels that each got.

#269 :memo: Add a section about gitmoji-changelog
  README.md
Labels: ✨ feature, 💬 needs-feedback

#457 📝 Removing GitHub project specification
  README.md
Labels: 😏 suggestion

#463 🔥 Remove :ok_hand: gitmoji
  src/__tests__/__snapshots__/pages.spec.js.snap
  src/data/gitmojis.json
Labels: 💥 breaking-change, 😜 emoji

#470 💬 Update 🔧 description
  src/__tests__/__snapshots__/pages.spec.js.snap
  src/data/gitmojis.json
Labels: ✨ improvement

#471 Remove platform specific gitmojis
  src/__tests__/__snapshots__/pages.spec.js.snap
  src/data/gitmojis.json
  src/styles/_includes/_vars.scss
Labels: 💥 breaking-change

#469 Add 🔨 gitmoji
  src/__tests__/__snapshots__/pages.spec.js.snap
  src/data/gitmojis.json
  src/styles/_includes/_vars.scss
Labels: 😜 emoji
